#!/bin/sh

BATCH=0;
SCENARIO=$1;
if [ $SCENARIO = "launch" ] || [ $SCENARIO = "clean" ] ; then
    CONFIG=$2;
fi

if [ $CONFIG = "all" ] ; then
    BATCH=1;
    echo "Batch detected!";
fi

if [ ! -f conf.d/$CONFIG.conf ] && [ $BATCH -eq 0 ]; then
    echo "Config doesn't exist under configs for $2."
    exit 1;
fi

# Launch a singular VM
if [ $SCENARIO = "launch" ] && [ $BATCH -eq 0 ]; then
    ./scripts/prepare-cloud-img.sh
    ./scripts/launch-virtual-machine.sh -c conf.d/$CONFIG.conf;
    exit 0;
# Clean a singular VM
elif [ $SCENARIO = "clean" ] && [ $BATCH -eq 0 ]; then
    ./scripts/cleanup.sh -c conf.d/$CONFIG.conf;
    exit 0;
# Launch all VMs
elif [ $SCENARIO = "launch" ] && [ $BATCH -eq 1 ]; then
    ./scripts/prepare-cloud-img.sh
    for config in conf.d/*.conf; do ./scripts/launch-virtual-machine.sh -c $config; done;
    exit 0;
# Clean all VMs
elif [ $SCENARIO = "clean" ] && [ $BATCH -eq 1 ]; then
    for config in conf.d/*.conf; do ./scripts/cleanup.sh -c $config; done;
    exit 0;
fi
